### ISSUE TITLE
fixed cafeteriaplan, handleBackArrow/handleClickArrow only if possible and... - [merged]

### ISSUE THREAD

**Issue by jmne** [jmne/ps-housetech-frontend#74]
In GitLab by @DrJohn17 on Jun 16, 2023, 18:13

_Merges dev-cafeteriaplan -> development_

Added Cafeteriaplan

## To-Do

- [x] Show the correct plan when loading the page
- [x] Clean up the files in /types -> move only necessary types to DishInformation.tsx
- [x] Create a file in /utils containing all the helper functions used
