### ISSUE TITLE
Wayfinder - Campus Map - [merged]

### ISSUE THREAD

**Issue by jmne** [jmne/ps-housetech-frontend#77]
In GitLab by @SimonBiel0301 on Jun 21, 2023, 13:03

_Merges dev-wayfinder_campus-map -> development_

# Campus Map

## Features

- Map showing the campus
- Map can be navigated without selecting persons

## To-Do

- [x] Implement a map showing the campus
- [x] Make Buildings searchable and highlightable
- [x] 'Base' state should show the campus map
- [x] 'Base' state should auto-scroll the list of persons

closes #7 
closes #10 
closes #11
